[project]
name = "pyclashbot"
version = "v0.0.0"
description = "Automated Clash Royale"
authors = [
    { name = "Matthew Miglio", email = "matthew@pyclashbot.app" },
    { name = "Martin Miglio", email = "code@martinmiglio.dev" },
]
requires-python = ">=3.12.0,<3.14"
readme = "README.md"
dependencies = [
    "opencv-python>=4.9.0,<5",
    "numpy>=2.2.1,<3",
    "pymemuc>=0.6.0,<0.7",
    "psutil>=6.1.0,<7",
    "freesimplegui>=5.2.0,<6",
]

[project.urls]
Homepage = "https://pyclashbot.app"

[dependency-groups]
build = [
    "cx-freeze>=8.3.0,<9",
    "packaging>=24.2",
    "requests>=2.32.4",
]
dev = [
    "pre-commit>=4.0.1,<5",
    "vulture~=2.13",
    "isort>=5.13.0,<6",
    "poethepoet>=0.36.0,<0.37",
    "notebook>=7.4.4,<8",
    "ipykernel>=6.29.2,<7",
    "matplotlib>=3.8.3,<4",
    "decorator>=5.1.1,<6",
    "ruff>=0.7.4,<0.8",
]

[tool.uv]
default-groups = ["build", "dev"]

[tool.hatch.build.targets.sdist]
include = [
    "README.md",
    "pyclashbot/detection/reference_images/**/*.png",
    "pyclashbot/__version__",
]

[tool.hatch.build.targets.wheel]
include = [
    "README.md",
    "pyclashbot/detection/reference_images/**/*.png",
    "pyclashbot/__version__",
]


[tool.ruff.lint]
select = [
    "C4",
    "E",
    "F",
    "W",
    "C90",
    "I",
    "INP",
    "ISC",
    "PGH",
    "PL",
    "UP",
    "N",
    "RUF",
    "TC",
]

ignore = [
    "PLR0913", # too-many-arguments
    "PLR0914", # too-many-locals
    "PLR0912", # too-many-branches
    "PLR0915", # too-many-statements
    "PLR0904", # too-many-public-methods
    "PLR0911", # too-many-return-statements
    "PLR0916", # too-many-boolean-expressions
    "PLR1702", # too-many-nested-blocks
    "PLR1704", # redefined-builtin
    "PLR0402", # uses-dict-iter-method
    "PLR0206", # property-with-parameters
    "PLW0603", # global-statement
    "PLR2004", # magic value used
    "PLR6301", # broad-except
    "PLR6201", # no-member
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar` 
    "TC002",   # Move third-party import `temporalio.client.Client` into a type-checking block
    "E402",    # Module level import not at top of file
    "C901",    # mccabe complexity
    "E501",
]

[tool.ruff]
line-length = 120

[tool.isort]
profile = "black"
