name: Pre-commit

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  pre-commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Install pre-commit hooks
        run: uvx pre-commit install

      - name: Run pre-commit on all files
        run: uvx pre-commit run --all-files
