name: Build windows package

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build package
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Build package
        run: |
          uv run --group build scripts/setup_msi.py bdist_msi --target-version ${{github.ref_name}}
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          prerelease: ${{startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc')}}
          generate_release_notes: true
          files: |
            ./dist/pyclashbot*.msi
      - name: Trigger Discord Webhook
        run: |
          uv run --group build scripts/trigger_discord_webhook.py \
            --version "${{ github.ref_name }}" \
            --url "${{ steps.release.outputs.url }}" \
            --webhook-code "${{ secrets.DISCORD_WEBHOOK_CODE }}" \
            ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'rc') && '--prerelease' || '' }}
        shell: bash
