name: Build windows package test

on:
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    name: Build package test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Build package
        run: |
          uv run --group build scripts/setup_msi.py bdist_msi --target-version v0.0.0
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/pyclashbot*.msi
          retention-days: 30
